version: "3"

services:
  php:
    build: ./.docker/php
    volumes:
      - .:/app
    working_dir: /app

  queue:
    build: ./.docker/php
    volumes:
      - .:/app
    working_dir: /app

  nginx:
    image: nginx:alpine
    volumes:
      - .:/app:ro
    working_dir: /app
    depends_on:
      - php
